services:

  postgres:
    image: postgres:18.6-trixie
    container_name: airflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow-postgres-data:/var/lib/postgresql

    networks:
      - spark-network


  airflow:
    build:
      context: ..
      dockerfile: docker/airflow/Dockerfile

    container_name: airflow
    restart: unless-stopped

    depends_on:
      - postgres
      - spark-master

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    volumes:
      - ../dags:/opt/airflow/dags
      - ../src:/opt/project/src
      - ../data:/opt/project/data

    ports:
      - "8080:8080"

    networks:
      - spark-network

    command: standalone


  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile

    container_name: spark-master
    restart: unless-stopped

    environment:
      SPARK_NO_DAEMONIZE: "true"

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    volumes:
      - ../src:/opt/project/src
      - ../data:/opt/project/data

    ports:
      - "7077:7077"
      - "8081:8080"

    networks:
      - spark-network

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"


  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile
      
    container_name: spark-worker
    restart: unless-stopped

    depends_on:
      - spark-master

    environment:
      SPARK_NO_DAEMONIZE: "true"

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    volumes:
      - ../src:/opt/project/src
      - ../data:/opt/project/data

    ports:
      - "8082:8081"

    networks:
      - spark-network

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - "2g"


networks:
  spark-network:
    driver: bridge


volumes:
  airflow-postgres-data: